python src/main.py birmingham 2 Tech Marine Navy Ai
python src/main.py manchester 2 Tech Marine Navy Ai
python src/main.py portsmouth 2 Tech Marine Navy Ai
python src/main.py surrey 2 Tech Marine Navy Ai
python src/main.py rmit 2 Tech Marine Navy Ai
python src/main.py sheffield 2 Tech Marine Navy Ai
python src/main.py leeds 2 Tech Marine Navy Ai
python src/main.py york 2 Tech Marine Navy Ai
python src/main.py uwe 2 Tech Marine Navy Ai
python src/main.py lancaster 2 Tech Marine Navy Ai
python src/main.py aberdeen 2 Tech Marine Navy Ai
python src/main.py bathspa 2 Tech Marine Navy Ai